1.Loading and Inspecting Data

In [28]:
import pandas as pd
df = pd.read_csv("data.csv")
df.head() 
df.shape 
df.info() 
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

I loaded the dataset and explored its contents. I checked the dataset structure, viewed the first rows, and examined the information and statistics of the data.

2.Selecting and Filtering

In [29]:
df['Duration'] 
df[['Duration', 'Pulse']]
df[df['Duration'] > 60]
df.loc[df["Duration"] > 30, "Pulse"]

0     110
1     117
2     103
3     109
4     117
5     102
6     110
7     104
9      98
10    103
11    100
12    100
13    106
14    104
15     98
16     98
17    100
18     90
19    103
20     97
21    108
22    100
23    130
24    105
25    102
26    100
27     92
28    103
29    100
30    102
31     92
Name: Pulse, dtype: int64

I selected specific columns and filtered rows based on conditions. This makes it easier to work with only the data that I need.

3.Cleaning Data

In [30]:
df.isnull().sum()
df["Calories"].fillna(df["Calories"].mean(), inplace=True)
df.drop_duplicates(inplace=True)
df.describe()

C:\Users\pc\AppData\Local\Temp\ipykernel_20800\3919180279.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Calories"].fillna(df["Calories"].mean(), inplace=True)

         Duration       Pulse    Maxpulse    Calories
count   31.000000   31.000000   31.000000   29.000000
mean    68.709677  103.612903  128.774194  306.541379
std     71.180144    7.935899   13.119222   66.365909
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  103.000000  128.000000  300.000000
75%     60.000000  107.000000  132.500000  345.300000
max    450.000000  130.000000  175.000000  479.000000

I checked for missing values and handled them using the mean value. I also removed duplicate rows to improve the quality of the dataset.

4.Grouping and Aggregation

In [31]:
df.groupby("Duration")["Pulse"].mean()
df.groupby("Duration").agg({"Pulse": "mean", "Calories": "max"})

               Pulse  Calories
Duration
30        109.000000     195.1
45        103.000000     406.0
60        103.521739     479.0
450       104.000000     253.3

I grouped the data by duration and calculated summary statistics. This helped me understand patterns and compare values between groups.